version = 0.1
[default.deploy.parameters]
stack_name = "quiz01-scraper-BOT-stk3"
resolve_s3 = true
s3_prefix = "quiz01-scraper-BOT-stk3"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=572867055940.dkr.ecr.us-east-1.amazonaws.com/quiz01scraperbotstk3a779287f/helloworldfunction19d43fc4repo"]
