version = 0.1
[default.deploy.parameters]
stack_name = "bot-playwright-stk1"
resolve_s3 = true
s3_prefix = "bot-playwright-stk1"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
