AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.10

  Sample SAM Template for quiz01-scraper-BOT

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        SCRAP01_DRIVER_LOCATION: /usr/bin/chromedriver
        SCRAP01_BINARY_LOCATION: /usr/bin/chromium-browser
        SCRAP01_QUIZ_URL_1: https://www.classmarker.com/online-test/start/?quiz=ncp5fac7839db8a1
        SCRAP01_API_KEY_1: eO8qdLLxsmRhc1OeKoFg9evcXyXetXwyo3N7ywf0
        SCRAP01_API_PUT_1: https://l8kpe9zcse.execute-api.us-east-1.amazonaws.com/Prod/quiz01
        SCRAP01_API_SEARCH_1: https://l8kpe9zcse.execute-api.us-east-1.amazonaws.com/Prod/quiz01/search/v2
        SCRAP01_API_ENDPOINT_1: https://1pjrb3wx65.execute-api.us-east-1.amazonaws.com/Prod
        SCRAP01_QUIZ_URL_2: https://www.classmarker.com/online-test/start/test-intro/?quiz=3qg5fac7589c0416
        SCRAP01_QUIZ_URL_3: https://www.classmarker.com/online-test/start/?quiz=ncp5fac7839db8a1

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./hello_world
      DockerTag: python3.10-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/docs"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
