name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-image:
    name: builds docker image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: downcase REPO
      run: |          
        ABC=$(echo 'print("MOISES".upper())' | python3.9 -)
        echo $ABC
    - uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_IMAGENAME}}:latest
          ghcr.io/moisesjurad0/${{secrets.DOCKERHUB_IMAGENAME}}:latest

